volumes:
  mysql_data:
  mongodb:
services:
    nginx:
      build: ./nginx/
      ports:
        - 80:80
  
      volumes:
        - ../:/var/www/html/

    php:
      build: ./php_code/
      expose:
        - 9000
      volumes:
        - ./php_code/:/var/www/html/

    db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: demo_db
        MYSQL_USER: mysql_user
        MYSQL_PASSWORD: mysql_user1!
      volumes:
        - mysql_data:/var/lib/mysql
      ports:
        - "3366:3306"
    
    mongo:
      image: mongo
      ports:
        - 27117:27017
      environment:
        - MONGO_INITDB_DATABASE=myMongoDB
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
      volumes:
        - ./mongo-entrypoint:/docker-entrypoint-initdb.d
        - mongodb:/data/db
      networks:
        - service-net

networks:
  service-net:
    external: true
